### PR TITLE
Update Gradle version to 6.1.1

### PR DESCRIPTION
**Pull request by PaulDaviesC**

### CODE REVIEW

**Comment by lbalmaceda** [comment]
@PaulBuilds Please, bump this to 0.11.0 as well https://github.com/auth0/jwks-rsa-java/blob/master/build.gradle#L52

**Comment by PaulDaviesC** [comment]
@lbalmaceda Also can we get this in 0.10 next version release itself?

**Comment by lbalmaceda** [comment]
Sure. Thanks for the changes

**Comment by PaulDaviesC** [comment]
@lbalmaceda any timeline for release of this change?

**Comment by lbalmaceda** [comment]
@PaulDaviesC this is already available 👍

**Comment by PaulDaviesC** [comment]
@lbalmaceda Thank you!

**Pull request merged**
