### PR TITLE
Add proxy

### PR DESCRIPTION
**Pull request by JosephWitthuhnTR**
### Changes

- Added methods to UrlJwkProvider and JwkProviderBuilder
- Careful not to modify existing method signatures or remove methods - change is backwards compatible
- We are using this library in an isolated network setting where some calls must go through an HTTP/HTTPS proxy, and other calls must not.
- This change is needed for use cases such as ours where we want to send this HTTP/HTTPS call through a proxy, but we don't want to set the global System Properties (which would impact other HTTP/HTTPS calls that we do not want to go through the same proxy as these calls must).

### References

I have recreated PR #91 - I totally messed up my branch and wanted to start with a clear PR so I wouldn't be pushing this change as a bunch of garbage commits, and instead keep the file history simple and clean.

### Testing

To test, simply invoke the new builder method and supply a proxy server. It can be as simple as:
`new java.net.Proxy(java.net.Proxy.Type.HTTP, new java.net.InetSocketAddress("proxy.mydomain.com", 8080))`

- [X] This change adds test coverage
- [ ] This change has been tested on the latest version of Java or why not
- [X] This change has been developed on Amazon Corretto 8, and uses a fairly simple Java API that has been around since Java 5

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [X] All existing and new tests complete without errors

### CODE REVIEW

**Comment by JosephWitthuhnTR** [comment]
@lbalmaceda I messed up my branch really bad, so I closed the PR and recreated the branch, rather than have a bunch of garbage commits to merge in. I was able to create one of the tests you suggested, but I got stuck trying to determine how to check what proxy gets passed into URL's openConnection method (since URL is a final class, I don't see a great way to do it, we cannot mock it or spy on what is passed in as parameters).

**Comment by lbalmaceda** [comment]
I'll take a look later this week and see if I can add something. Stay tuned 👍

**Comment by lbalmaceda** [comment]
@JosephWitthuhnTR I still wasn't able to give this a try locally, but I'm tracking it internally under `SDK-1936`. I hope to bring this up for working on it the next week.

**Comment by lbalmaceda** [comment]
@JosephWitthuhnTR apologies for the delay. This is still on my queue 👍

**Comment by lbalmaceda** [comment]
@JosephWitthuhnTR hey! I was able to add the missing tests but I'm having trouble to push the changes to this PR, since I don't own the fork. I think it might be to [this setting](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) not being enabled on your side. Do you mind checking, please? Otherwise, I'd have to push this to a new PR.

**Comment by JosephWitthuhnTR** [comment]
@lbalmaceda I don't see that option anywhere. I think you would have to do a pull request to get your commit into https://github.com/thomsonreuters/jwks-rsa-java/tree/add-proxy, I approve it to add the change to my code, and then it would appear as part of that pull request.

Or, if you send me the change, I can just commit it to my branch to get it added here.

**Comment by lbalmaceda** [comment]
I've created a patch. Copy the contents into a new file e.g. `java.patch`. Sitting on the root of the repo, you could apply it using the following:

```
$ git am <patch_file>
```

And then just push to this branch so the PR gets updated. 

This is the content:


```diff
From d0be4978e141f69b3de1604bb0f9f56314a01eb8 Mon Sep 17 00:00:00 2001
From: Luciano Balmaceda <balmacedaluciano@gmail.com>
Date: Mon, 28 Sep 2020 19:23:38 -0300
Subject: [PATCH] add tests for ensuring the proxy is set to the URLConnection
 instance

---
 .../com/auth0/jwk/JwkProviderBuilder.java     |  2 +
 .../com/auth0/jwk/JwkProviderBuilderTest.java |  6 +-
 .../com/auth0/jwk/UrlJwkProviderTest.java     | 70 ++++++++++++++++---
 3 files changed, 64 insertions(+), 14 deletions(-)

diff --git a/src/main/java/com/auth0/jwk/JwkProviderBuilder.java b/src/main/java/com/auth0/jwk/JwkProviderBuilder.java
index c4488a9..1b1e06c 100644
--- a/src/main/java/com/auth0/jwk/JwkProviderBuilder.java
+++ b/src/main/java/com/auth0/jwk/JwkProviderBuilder.java
@@ -48,6 +48,7 @@ public class JwkProviderBuilder {
      * <br><br> For example, when the domain is "samples.auth0.com"
      * the jwks url that will be used is "https://samples.auth0.com/.well-known/jwks.json"
      * <br><br> Use {@link #JwkProviderBuilder(URL)} if you need to pass a full URL.
+     *
      * @param domain where jwks is published
      * @throws IllegalStateException if domain is null
      * @see UrlJwkProvider#UrlJwkProvider(String)
@@ -116,6 +117,7 @@ public class JwkProviderBuilder {
 
     /**
      * Sets the proxy to use for the connection.
+     *
      * @param proxy proxy server to use when making this connection
      * @return the builder
      */
diff --git a/src/test/java/com/auth0/jwk/JwkProviderBuilderTest.java b/src/test/java/com/auth0/jwk/JwkProviderBuilderTest.java
index 3689ce7..c54611c 100644
--- a/src/test/java/com/auth0/jwk/JwkProviderBuilderTest.java
+++ b/src/test/java/com/auth0/jwk/JwkProviderBuilderTest.java
@@ -10,9 +10,7 @@ import java.net.URL;
 import java.util.concurrent.TimeUnit;
 
 import static com.auth0.jwk.UrlJwkProvider.WELL_KNOWN_JWKS_PATH;
-import static org.hamcrest.Matchers.equalTo;
-import static org.hamcrest.Matchers.instanceOf;
-import static org.hamcrest.Matchers.notNullValue;
+import static org.hamcrest.Matchers.*;
 import static org.junit.Assert.assertThat;
 
 public class JwkProviderBuilderTest {
@@ -146,7 +144,7 @@ public class JwkProviderBuilderTest {
         UrlJwkProvider urlJwkProvider = (UrlJwkProvider) provider;
         assertThat(urlJwkProvider.url.toString(), equalTo(urlToJwksWithSubPath));
     }
-    
+
     @Test
     public void shouldCreateForUrlAndProxy() throws Exception {
         URL url = new URL(normalizedDomain + WELL_KNOWN_JWKS_PATH);
diff --git a/src/test/java/com/auth0/jwk/UrlJwkProviderTest.java b/src/test/java/com/auth0/jwk/UrlJwkProviderTest.java
index 8e0db35..b62623b 100644
--- a/src/test/java/com/auth0/jwk/UrlJwkProviderTest.java
+++ b/src/test/java/com/auth0/jwk/UrlJwkProviderTest.java
@@ -5,6 +5,8 @@ import org.junit.Rule;
 import org.junit.Test;
 import org.junit.rules.ExpectedException;
 import org.mockito.ArgumentCaptor;
+import org.mockito.invocation.InvocationOnMock;
+import org.mockito.stubbing.Answer;
 
 import java.io.IOException;
 import java.lang.ref.WeakReference;
@@ -201,21 +203,45 @@ public class UrlJwkProviderTest {
 
         // The weak reference is just a safeguard against objects not being released
         // for garbage collection
-        private final WeakReference<URLConnection> value;
+        private final WeakReference<URLConnection> urlConnectionValue;
+        public WeakReference<URL> urlUsed;
+        public WeakReference<Proxy> proxyUsed;
 
         public MockURLStreamHandlerFactory(URLConnection urlConnection) {
-            this.value = new WeakReference<URLConnection>(urlConnection);
+            this.urlConnectionValue = new WeakReference<>(urlConnection);
+            this.urlUsed = new WeakReference<>(null);
+            this.proxyUsed = new WeakReference<>(null);
         }
 
         public void clear() {
-            this.value.clear();
+            clearUsed();
+            this.urlConnectionValue.clear();
+        }
+
+        private void clearUsed() {
+            this.urlUsed.clear();
+            this.proxyUsed.clear();
+        }
+
+        private void setUsed(URL u, Proxy p) {
+            clearUsed();
+            urlUsed = new WeakReference<>(u);
+            proxyUsed = new WeakReference<>(p);
         }
 
         @Override
         public URLStreamHandler createURLStreamHandler(String protocol) {
             return "mock".equals(protocol) ? new URLStreamHandler() {
-                protected URLConnection openConnection(URL url) throws IOException {
-                    return value.get();
+                @Override
+                protected URLConnection openConnection(URL u, Proxy p) throws IOException {
+                    setUsed(u, p);
+                    return urlConnectionValue.get();
+                }
+
+                @Override
+                protected URLConnection openConnection(URL u) throws IOException {
+                    setUsed(u, null);
+                    return urlConnectionValue.get();
                 }
             } : null;
         }
@@ -224,32 +250,56 @@ public class UrlJwkProviderTest {
     @Test
     public void shouldConfigureURLConnection() throws Exception {
         URLConnection urlConnection = mock(URLConnection.class);
+        when(urlConnection.getInputStream()).thenAnswer(new Answer<Object>() {
+            @Override
+            public Object answer(InvocationOnMock invocation) throws Throwable {
+                return getClass().getResourceAsStream("/jwks.json");
+            }
+        });
 
         // Although somewhat of a hack, this approach gets the job done - this method can 
         // only be called once per virtual machine, but that is sufficient for now.
         MockURLStreamHandlerFactory mockFactory = new MockURLStreamHandlerFactory(urlConnection);
         URL.setURLStreamHandlerFactory(mockFactory);
-        when(urlConnection.getInputStream()).thenReturn(getClass().getResourceAsStream("/jwks.json"));
 
+        URL url = new URL("mock://localhost");
         int connectTimeout = 10000;
         int readTimeout = 15000;
 
-        UrlJwkProvider urlJwkProvider = new UrlJwkProvider(new URL("mock://localhost"), connectTimeout, readTimeout);
+        //Test creation: without Proxy
+        UrlJwkProvider urlJwkProvider = new UrlJwkProvider(url, connectTimeout, readTimeout);
+        assertThat(urlJwkProvider.proxy, is(nullValue()));
+
         Jwk jwk = urlJwkProvider.get("NkJCQzIyQzRBMEU4NjhGNUU4MzU4RkY0M0ZDQzkwOUQ0Q0VGNUMwQg");
         assertNotNull(jwk);
+        assertThat(mockFactory.urlUsed.get(), is(url));
+        assertThat(mockFactory.proxyUsed.get(), is(nullValue()));
+
+        //Test creation: with Proxy
+        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 8080));
+        URL pUrl = new URL("mock://localhost");
+        UrlJwkProvider pUrlJwkProvider = new UrlJwkProvider(pUrl, connectTimeout, readTimeout, proxy);
+        assertThat(pUrlJwkProvider.proxy, is(proxy));
+
+        Jwk pJwk = pUrlJwkProvider.get("NkJCQzIyQzRBMEU4NjhGNUU4MzU4RkY0M0ZDQzkwOUQ0Q0VGNUMwQg");
+        assertNotNull(pJwk);
+        assertThat(mockFactory.urlUsed.get(), is(pUrl));
+        Proxy usedProxy = mockFactory.proxyUsed.get();
+        assertThat(usedProxy, is(notNullValue()));
+        assertThat(usedProxy.address(), is(proxy.address()));
 
         //Test 1: Configuration
         //Request Timeout assertions
         ArgumentCaptor<Integer> connectTimeoutCaptor = ArgumentCaptor.forClass(Integer.class);
-        verify(urlConnection).setConnectTimeout(connectTimeoutCaptor.capture());
+        verify(urlConnection, times(2)).setConnectTimeout(connectTimeoutCaptor.capture());
         assertThat(connectTimeoutCaptor.getValue(), is(connectTimeout));
 
         ArgumentCaptor<Integer> readTimeoutCaptor = ArgumentCaptor.forClass(Integer.class);
-        verify(urlConnection).setReadTimeout(readTimeoutCaptor.capture());
+        verify(urlConnection, times(2)).setReadTimeout(readTimeoutCaptor.capture());
         assertThat(readTimeoutCaptor.getValue(), is(readTimeout));
 
         //Request Headers assertions
-        verify(urlConnection).setRequestProperty("Accept", "application/json");
+        verify(urlConnection, times(2)).setRequestProperty("Accept", "application/json");
 
         //Test 2: Network errors
         Exception capturedException = null;
-- 
2.19.2


```

Let me know if that works for you.

**Comment by JosephWitthuhnTR** [comment]
@lbalmaceda Done!

**Comment by lbalmaceda** [comment]
@JosephWitthuhnTR Thanks! One last ask, it seems out of date with `auth0/master`. Would you mind rebasing, please? I'm not given that option in the GH UI.

**Comment by JosephWitthuhnTR** [comment]
@lbalmaceda I believe I got that done too, now.

**Review by lbalmaceda — APPROVED** [review]

**Comment by lbalmaceda** [comment]
Thank you!

**Pull request merged**
