### PR TITLE
Remove algorithm (alg tag) from mandatory Jwk attributes

### LINKED ISSUE #6: optional 'alg'
According to this spec: https://tools.ietf.org/html/rfc7517#section-4.4 'alg' jwks parameter is optional.

Now Jwk.fromValues will throw IllegalArgumentException when 'alg' is not present.

https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/Jwk.java#L69

### PR DESCRIPTION
**Pull request by Colin-b**
As this is an optional value as described in https://tools.ietf.org/html/rfc7517#section-4.4

It fixes #6

### CODE REVIEW

**Comment by Colin-b** [comment]
Hi
Apologies, I'll try to add some this week.

Best regards

**Comment by puttzy** [comment]
@Colin-b @lbalmaceda 

We're dependent on this.  It looks like the only thing that is needed is:
`@Test

    public void shouldThrowInvalidArgumentException() throws Exception {

        final String kid = randomKeyId();
        Map<String, Object> values = publicKeyValues(kid);
        values.remove("alg");
        expectedException.expect(IllegalArgumentException.class);
        Jwk.fromValues(values);
    }`

I can add a PR to @Colin-b repo or add that test and create my own PR on this project (but I don't want to steal his thunder)

**Comment by lbalmaceda** [comment]
@puttzy @Colin-b 
should actually add at least 3 tests:
- throw when calling `fromValues()` and `kid == null`
- throw when calling `fromValues()` and `kty == null`
` NOT throw when calling `fromValues()` and `alg == null`

**Comment by Colin-b** [comment]
Thanks for the test case, I'll update the PR tomorrow around noon.

**Comment by puttzy** [comment]
@Colin-b here's the three test cases that I think will be needed

`


    @Test
    public void shouldThrowInvalidArgumentExceptionMissingKID() throws Exception {
        final String kid = randomKeyId();
        Map<String, Object> values = publicKeyValues(kid);
        values.remove("kid");
        expectedException.expect(IllegalArgumentException.class);
        Jwk.fromValues(values);
    }

    @Test
    public void shouldThrowInvalidArgumentExceptionMissingKTY() throws Exception {
        final String kid = randomKeyId();
        Map<String, Object> values = publicKeyValues(kid);
        values.remove("kty");
        expectedException.expect(IllegalArgumentException.class);
        Jwk.fromValues(values);
    }

    @Test
    public void shouldReturnKeyWihMissingAlgParam() throws Exception {
        final String kid = randomKeyId();
        Map<String, Object> values = publicKeyValues(kid);
        values.remove("alg");
        Jwk jwk = Jwk.fromValues(values);
        assertThat(jwk.getPublicKey(), notNullValue());
    }
`

**Comment by Colin-b** [comment]
Thanks a lot @puttzy , test cases have been appended

**Comment by lbalmaceda** [comment]
I've found an issue with travis, CI passes when it shouldn't as there was a compile error when calling the `publicKeyValues` method with 2 parameters, when the method on that class has 1. (probably a merge issue). I'm fixing it on your branch so don't worry. 👍

**Pull request merged**
