### PR TITLE
Add proxy

### PR DESCRIPTION
**Pull request by JosephWitthuhnTR**
### Changes

- Added methods to UrlJwkProvider and JwkProviderBuilder
- Careful not to modify existing method signatures or remove methods - change is backwards compatible
- We are using this library in an isolated network setting where some calls must go through an HTTP/HTTPS proxy, and other calls must not.
- This change is needed for use cases such as ours where we want to send this HTTP/HTTPS call through a proxy, but we don't want to set the global System Properties (which would impact other HTTP/HTTPS calls that we do not want to go through the same proxy as these calls must).

### References

I am not aware of any references. We identified this as a need for our projects and have been working around the proxy limitation locally, but we wanted to contribute this change back rather than maintain it as our own "side fix/enhancement" for the issue.

### Testing

To test, simply invoke the new builder method and supply a proxy server. It can be as simple as:
`new java.net.Proxy(java.net.Proxy.Type.HTTP, new java.net.InetSocketAddress("proxy.mydomain.com", 8080))`

- [ ] This change adds test coverage
- [ ] This change has been tested on the latest version of Java or why not
- [X] This change has been developed on Amazon Corretto 8, and uses a fairly simple Java API that has been around since Java 5

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [X] All existing and new tests complete without errors

### CODE REVIEW

**Comment by lbalmaceda** [comment]
Thanks for this addition. Recently our team has identified some gaps in how these providers are being instantiated via their public constructors. Given that introducing this proxy parameter would mean adding yet another constructor to support that, we think having an "options" object is going to scale better as it's future proof. This way, things such as timeout, proxy, and anything we add later, could be added to the options class instead of having a new constructor in place. WDYT?

Also, given the library is still on major 0, I think we can make some breaking refactors:
- The entry point would keep being the provider builder. That class will not suffer breaking changes. The `proxied` method you added is enough.
- URL provider could have only 2 constructors, one with the URL and another with the URL + options. The timeout constructor would be removed, replaced with that options object. On that object is where timeout and proxy options would live with setters.
- A changelog note could indicate on our next minor how to migrate to those using the URLProvider directly and not through the builder.

**Comment by JosephWitthuhnTR** [comment]
@lbalmaceda I definitely agree with you on that as a vision, and had some of the same thoughts as I was looking at this code. My goal with this particular commit was to make a compact, isolated, non-breaking change. Do you want me to try to make the changes you are describing as part of this PR, or would that be better done as a separate "refactor" commit and pull request?

I think it would make my little addition into a fairly significant (breaking) change.

**Comment by lbalmaceda** [comment]
I appreciate you keeping compatibility here. If you like I can accept this PR as is, and plan for that Options change on a separate PR before the next release.

**Comment by JosephWitthuhnTR** [comment]
I'd prefer to keep this change on its own (I don't think it hurts anything), and maybe look at adding an Options constructor as a separate change.

My two cents: adding an Options constructor instead of replacing the existing ones, but deprecating the others for removal in a future release feels like the optimal path

**Comment by lbalmaceda** [comment]
>My two cents: adding an Options constructor instead of replacing the existing ones, but deprecating the others for removal in a future release, feels like the optimal path

I would definitely do this for any major version other than 0. But doing it now on the current major wouldn't break semver. If we can make this small breaking change and document it, I'd take my chance.

**Comment by lbalmaceda** [comment]
Would you mind rebasing this branch, please? I can cut a release this Wednesday.

**Comment by JosephWitthuhnTR** [comment]
@lbalmaceda I think this should be good to go now.

**Comment by lbalmaceda** [comment]
@JosephWitthuhnTR for some reason it's still showing as out of date with master. Something I forgot to ask before is the unit tests. We require every introduced change to have its companion unit tests. Would you add them, please? You can base on [this](https://github.com/auth0/jwks-rsa-java/blob/master/src/test/java/com/auth0/jwk/JwkProviderBuilderTest.java#L134-L146) for checking that the proxy is passed and maybe something [here](https://github.com/auth0/jwks-rsa-java/blob/master/src/test/java/com/auth0/jwk/UrlJwkProviderTest.java#L225) for asserting the proxy is actually being used. Note for this last one you'd need to write the test in that same test method. The comments will guide you.

**Comment by JosephWitthuhnTR** [comment]
@lbalmaceda I think I got my branch up-to-date now. I had previously created a pull request and picked rebase, but now I did a pull request and did a merge, and it looks like it is showing up to date.

My work day is just about over, but I will try to commit the unit tests tomorrow.

**Comment by JosephWitthuhnTR** [comment]
I made a big enough mess of this that I closed this branch and restarted it as PR #94 (with one commit instead of over ten).

**Pull request closed without merging**
