### PR TITLE
Improved JwkProvider

### PR DESCRIPTION
**Pull request by skjolber**
### Changes

Almost a full rewrite; mandates a new major version release due to breaking changes.

New features:
 - preemptive cache refresh in background
 - guard against transient network issues (by retrying once)
 - guard against temporary network problem / outage
 - protection against multiple threads refreshing the cache at once (with the same data, solves #70) 
 - best-effort flush of keys no longer available at the Authorization Server (solves #69))
 - updated documentation

The underlying implementation has been refactored to work on a list of JWK (and not individual keys). In several ways, this simplifies things.

### Testing

- [x] This change adds test coverage
- [x] This change has been tested on the latest version of Java or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors

### CODE REVIEW

**Comment by skjolber** [comment]
@lbalmaceda  I realize this is a lot of changes, but feel that this is the right home for this code. 

An initial feedback on when (if?) this PR can be reviewed / merged would be much appriciated.

**Comment by lbalmaceda** [comment]
@skjolber Remember this library is still on "major 0", so we should be able to make "breaking changes" without bumping the major according to semver. Given that it's almost a complete rewrite, I'd suggest adding a migration guide once we consider the diff is OK. It's a long shot but I can leave a quick review this week. I've added it to my backlog.

**Comment by lbalmaceda** [comment]
@skjolber 
We've evaluated the PR with the team and here are the conclusions. 
- We value the extensibility of the library: Having a `JwkProvider` class with some default implementations is desired. We consider the "Outage" and "Preemptive" providers to be border-case scenarios that are not be part of this library and can be easily implemented by the user on their side.
- Speaking of threads, we're no experts on the matter but we know that a mis-implementation can lead to real bad damage on the application's runtime on the server side. 
- We are not entirely convinced on having our own cache implementation (like the one on this PR). We think this decision should be ultimately left for the user to take, using their desired library or class (e.g. the `javax.cache` API). Given that this library is currently shipping with one cache implementation (using Google's Guava) we decided we will keep that class in hand.
- Additionally, caching could be handled at an Http Client level if we expose an interface for the user to plug their client in. Support for proxy, custom timeouts, etc are also examples of configurations we can open up in that way. 

Does this changes sound OK to you? In summary, we would like this PR to:
1. Remove the `RetryingJwksProvider`, `CachedJwksProvider`, `OutageCachedJwksProvider` and `PreemptiveCachedJwksProvider` classes. If you decide to host them somewhere (e.g. a GH Gist) we can link to them later from our Readme.
2. Keep the `GuavaCachedJwkProvider` class (or/and adapt it to the changes on this PR).
3. Optionally, expose an interface to a generic Http Client that the user can plug in and customize. This can be on a separate PR if you want.

**Comment by skjolber** [comment]
Removing the providers we need is not a great alternative - can't just ship it off to a Gist, it must be available as compiled code (in a public repo). Hosting this code in our own Github is now my best use of time; adding an Auth0 as a 'flavour'. There is also some (more or less) parallel issues for how to best share an access-token on a server.

I can absolutely understand you don't want to take in code you're not able to properly evaluate. As an alternative implementation I suggest you check out guavas LoadingCache, see also [HttpsJwks](https://bitbucket.org/b_c/jose4j/src/master/src/main/java/org/jose4j/jwk/HttpsJwks.java).

As far as I can see, the current implementation will result in a bit of thread spagetti for a server (under heavy load); proportional to the time it takes to setup an SSL connection and download the keys. On my machine (for a fiber connection) getting the keys over SSL using Chrome takes 0.1 seconds. Response times will be correspondingly affected for those requests arriving within the 0.1 second window. Downstream the autorization server will have to handle several requests instead of a single. 

The retrying provider saves 1-2 errors per week in our setup. We have > 100 virtual machines and fetch the (public) keys relatively often.

Outage will of course not occour very often, but it is better to be a bit flexiable on authorization server and/or cloud infrastructure gliches (especially network-related issues).

**Comment by lbalmaceda** [comment]
Thanks for sharing the details on your use cases. I'll make sure to communicate them back to the team as well.

**Comment by skjolber** [comment]
@lbalmaceda FYI here is the resulting open source project: https://github.com/entur/jwt-resource-server

**Pull request closed without merging**
