### PR TITLE
Support EC key type in JWK #87

### PR DESCRIPTION
**Pull request by wilddog1979**
### Changes

Abstracted JWK and kept the original implementation as key type RSA, and Elliptic curve implementation added (fromValues factory method adjusted to return the right implementation according to kty value).

### References

RFC 7517 is defining kty value EC for Elliptic Curve keys (https://tools.ietf.org/html/rfc7517#section-4.1)
RFC 5480 is containing name cross references for curve name - used in crv field of JWK entry - and Java cryptography API  (https://tools.ietf.org/html/rfc5480#section-2.1.1.1)
Bouncy Castle ECNamedCurveTable is used to get the Elliptic Curve parameter specification (https://www.bouncycastle.org/docs/docs1.5on/org/bouncycastle/jce/ECNamedCurveTable.html#getParameterSpec-java.lang.String-)

### Testing

It is possible to generate Elliptic Curve key pairs and feed the library through a mock key store. This can be used to obtain public key definition and validate a signature. 

- [x] This change adds test coverage
- [x] This change has been tested on the latest version of Java or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors

### CODE REVIEW

**Comment by lbalmaceda** [comment]
@wilddog1979 hey, sorry for the late response here. Will you still be around to make any required changes that might come up from a detailed PR review? We can give this PR a detailed review next week. In the meantime, something we would like to avoid is making breaking changes. e.g. changing the jwk class to be abstract or changing the visibility of the methods. We also have some questions about the introduced bouncycastle dependency. But will follow up soon. Thanks

**Comment by wilddog1979** [comment]
@lbalmaceda No worries. Take your time. My suggestion to make Jwt class to be abstract because it would express better the fact that Jwk has two types: RSA and EC. Even beyond the expression, this class may act as a factory class of the two subtypes. However I understand your motivation to not change the type of the class and the visibility of the methods. My suggestion in that case could be to add an interface to JwKey where common method declarations may take place and Jwk class would be one implementor where RSA key type implementation would be. The name would be misleading (Jwk instead of JwkRsa). And we are going into naming issue. Since you started this project as jwks-rsa-java, it looks like you wanted to focus on RSA keys and conceptually my initiative with EC keys derailing or at least repurposing the project. So it is a cunceptual question. Better if you decide if this is not a problem on your side. No hard feelings if you not wish to go down this road.

The other part of your question is the usage of bouncycastle dependency. I needed this dependency to initialize EC parameter specs before extracting x and y values of the key. I looked into the source code of bouncycastle and I am able to extract the necessary parameters - ugly BigInteger constants. That way I am able to avoid the usage of this dependency. I noticed higher version of this dependency is not exposing ECNamedCurveTable.getParameterSpec method therefore I have to figure out another way.

**Comment by wilddog1979** [comment]
Two major changes added to the pull request
- I think I resolved Jwk braking changes with minimal or no impact at all on the interface of this class. Note that because of the abstraction layer some common methods with Elliptic Curve was moved up to parent class.
- BouncyCastle dependency was removed. I left references in the source to RFC's and corresponding supporting materials.

**Comment by lbalmaceda** [comment]
@wilddog1979 hello 👋 and apologies for the time it took us to come back to you. 

We tested this PR locally parsing an EC JWK using ES256 and curve P-256 and run into an exception around the algorithm type. We also came across another PR recently opened that intends to fill the same feature. We’ve tested it with the same EC JWK and it works as expected. We plan to proceed to merge that PR.

I wanted to reach out to you first so you can verify if this other PR is a fit for your use case and if you can test it on your side as well to check that it works as expected for you as well. I'll wait a few days to hear from you and in the meantime will add a review in there. We thank you for your contribution 🙇 .

The PR is #110.

**Comment by lbalmaceda** [comment]
I'm closing this as we've merged the PR referenced above. This will be available on 0.16.0. Thanks again for your contribution!

**Pull request closed without merging**
